-- NCPOR Polar Portal: cloud-first schema. Apply with `supabase db push` to the linked Cloud project.
create extension if not exists pgcrypto;
create type public.content_status as enum ('DRAFT','REVIEW','APPROVED','PUBLISHED','ARCHIVED');
create type public.region as enum ('Antarctica','Arctic','Southern Ocean');
create table public.organizations (id uuid primary key default gen_random_uuid(), name text unique not null, acronym text, description text, website text, created_at timestamptz not null default now());
create table public.research_topics (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, description text, parent_id uuid references public.research_topics(id));
create table public.stations (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, region public.region not null, latitude numeric(8,5) check (latitude between -90 and 90), longitude numeric(8,5) check (longitude between -180 and 180), description text, research_focus text, active_status boolean default true, organization_id uuid references public.organizations(id), created_at timestamptz not null default now());
create table public.expeditions (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, short_title text, region public.region not null, start_date date, end_date date, summary text not null, objectives text, status public.content_status not null default 'DRAFT', featured boolean default false, primary_station_id uuid references public.stations(id), provenance text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.publications (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, abstract text, year smallint check (year between 1900 and 2200), journal text, doi text unique, external_url text, access_status text default 'OPEN', status public.content_status not null default 'DRAFT', provenance text, created_at timestamptz not null default now());
create table public.datasets (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, short_description text not null, full_description text, geographic_area text, temporal_start date, temporal_end date, access_status text default 'OPEN', doi text unique, external_url text, license text, provenance text, featured boolean default false, status public.content_status not null default 'DRAFT', created_at timestamptz not null default now());
create table public.media_assets (id uuid primary key default gen_random_uuid(), slug text unique not null, type text not null check (type in ('IMAGE','VIDEO','AUDIO','OTHER')), title text not null, caption text, alt_text text, file_key text, thumbnail_key text, mime_type text, rights text, license text, access_status text default 'OPEN', status public.content_status not null default 'DRAFT', created_at timestamptz not null default now());
create table public.expedition_publications (expedition_id uuid references public.expeditions(id) on delete cascade, publication_id uuid references public.publications(id) on delete cascade, primary key(expedition_id, publication_id));
create table public.expedition_datasets (expedition_id uuid references public.expeditions(id) on delete cascade, dataset_id uuid references public.datasets(id) on delete cascade, primary key(expedition_id, dataset_id));
create table public.newsletter_subscriptions (id uuid primary key default gen_random_uuid(), email text unique not null, status text not null default 'DEMO_PENDING_PROVIDER', created_at timestamptz not null default now());
alter table public.organizations enable row level security; alter table public.research_topics enable row level security; alter table public.stations enable row level security; alter table public.expeditions enable row level security; alter table public.publications enable row level security; alter table public.datasets enable row level security; alter table public.media_assets enable row level security;
alter table public.expedition_publications enable row level security; alter table public.expedition_datasets enable row level security; alter table public.newsletter_subscriptions enable row level security;
create policy "Published expeditions are public" on public.expeditions for select using (status = 'PUBLISHED');
create policy "Published publications are public" on public.publications for select using (status = 'PUBLISHED');
create policy "Published datasets are public" on public.datasets for select using (status = 'PUBLISHED');
create policy "Published media are public" on public.media_assets for select using (status = 'PUBLISHED');
create policy "Stations are public" on public.stations for select using (true);
create policy "Topics are public" on public.research_topics for select using (true);
create policy "Organizations are public" on public.organizations for select using (true);
-- Admin mutation policies deliberately belong in a follow-up role migration; no browser client can write by default.
